name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1

    - uses: aarnott/nbgv@v0.4.0

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          3.1.x
          6.0.x
     
    - name: dotnet build
      run: dotnet build BedrockFramework.sln -c Release
      
    - name: dotnet test
      run: dotnet test BedrockFramework.sln -c Release --no-build

    - name: dotnet pack
      run: dotnet pack BedrockFramework.sln -c Release --no-build --include-source --include-symbols

    - name: setup nuget
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: NuGet/setup-nuget@v1.0.5
      with:
        nuget-version: latest

    - name: Set API key
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: nuget setapikey ${{ secrets.FEEDZ_TOKEN }} -Config nuget.config -Source https://f.feedz.io/hallofmeat/bedrockframework/nuget/index.json

    - name: Set symbols API key
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: nuget setapikey ${{ secrets.FEEDZ_TOKEN }} -Config nuget.config -Source https://f.feedz.io/hallofmeat/bedrockframework/symbols

    - name: push packages
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: dotnet nuget push **/*.nupkg -s https://f.feedz.io/hallofmeat/bedrockframework/nuget/index.json -ss https://f.feedz.io/hallofmeat/bedrockframework/symbols --skip-duplicate
